# Generated by Django 3.1.3 on 2021-06-27 12:01

import cross_book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.IntegerField(default=0, validators=[cross_book.models.Item.validate_choice], verbose_name='カテゴリ'),
        ),
    ]
