# Generated by Django 3.1.3 on 2021-06-27 23:31

import cross_book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0002_auto_20210627_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.IntegerField(choices=[(0, '文学・エッセイ'), (1, 'ビジネス・経済'), (2, '漫画・ラノベ'), (3, '趣味・実用'), (4, '学問・資格・教育'), (5, '絵本・児童書'), (6, 'エンタメ'), (7, '雑誌・ムック'), (8, 'その他')], default=0, validators=[cross_book.models.Item.validate_choice], verbose_name='カテゴリ'),
        ),
    ]
