# Generated by Django 3.1.3 on 2021-06-27 23:33

import cross_book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0003_auto_20210628_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.IntegerField(choices=[(0, '選択してください'), (1, '文学・エッセイ'), (2, 'ビジネス・経済'), (3, '漫画・ラノベ'), (4, '趣味・実用'), (5, '学問・資格・教育'), (6, '絵本・児童書'), (7, 'エンタメ'), (8, '雑誌・ムック'), (9, 'その他')], default=0, validators=[cross_book.models.Item.validate_choice], verbose_name='カテゴリ'),
        ),
    ]
