# Generated by Django 3.0.3 on 2021-03-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0003_auto_20210305_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_text',
            field=models.TextField(blank=True, max_length=250, verbose_name='プロフィール文'),
        ),
    ]
