# Generated by Django 3.0.3 on 2021-03-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0003_auto_20210327_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.IntegerField(choices=[(0, '選択してください'), (1, '未使用'), (2, '未使用に近い状態'), (3, '目立った傷や汚れなし'), (4, 'やや傷や汚れあり'), (5, '傷や汚れあり'), (6, '全体的に状態が悪い')], default=0, verbose_name='商品の状態'),
        ),
    ]
