# Generated by Django 3.1.3 on 2021-06-28 17:49

import cross_book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0003_auto_20210629_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default='選択肢してください', max_length=255, validators=[cross_book.models.Item.validate_category], verbose_name='カテゴリ'),
        ),
    ]
