# Generated by Django 3.1.7 on 2021-04-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0003_auto_20210406_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroom',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
