# Generated by Django 3.0.3 on 2021-03-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0005_auto_20210306_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ImageField(null=True, upload_to='item_pics'),
        ),
        migrations.AlterField(
            model_name='item',
            name='shipping_area',
            field=models.IntegerField(choices=[(0, '選択してください'), (1, '北海道'), (2, '青森県'), (3, '岩手県'), (4, '宮城県'), (5, '秋田県'), (6, '山形県'), (7, '福島県'), (8, '茨城県'), (9, '栃木県'), (10, '群馬県'), (11, '埼玉県'), (12, '千葉県'), (13, '東京都'), (14, '神奈川県'), (15, '新潟県'), (16, '富山県'), (17, '石川県'), (18, '福井県'), (19, '山梨県'), (20, '長野県'), (21, '岐阜県'), (22, '静岡県'), (23, '愛知県'), (24, '三重県'), (25, '滋賀県'), (26, '京都府'), (27, '大阪府'), (28, '兵庫県'), (29, '奈良県'), (30, '和歌山県'), (31, '鳥取県'), (32, '島根県'), (33, '岡山県'), (34, '広島県'), (35, '山口県'), (36, '徳島県'), (37, '香川県'), (38, '愛媛県'), (39, '高知県'), (40, '福岡県'), (41, '佐賀県'), (42, '長崎県'), (43, '熊本県'), (44, '大分県'), (45, '宮崎県'), (46, '鹿児島県'), (47, '沖縄県'), (48, '未定')], default=0, verbose_name='発送元の地域'),
        ),
        migrations.AlterField(
            model_name='item',
            name='shipping_day',
            field=models.IntegerField(choices=[(0, '選択してください'), (1, '1~2日で発送'), (2, '2~3日で発送'), (3, '4~7日で発送')], default=0, verbose_name='発送までの日数'),
        ),
    ]
