# Generated by Django 3.0.3 on 2021-03-27 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0005_auto_20210327_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
