# Generated by Django 3.1.7 on 2021-04-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0005_room_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRoom',
        ),
    ]
