# Generated by Django 3.0.3 on 2021-03-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0006_auto_20210308_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='画像'),
        ),
    ]
