# Generated by Django 3.0.3 on 2021-03-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0007_auto_20210329_0947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tag',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.IntegerField(choices=[(0, '選択してください'), (1, '文学・エッセイ'), (2, 'ビジネス・経済'), (3, '漫画・ラノベ'), (4, '趣味・実用'), (5, '学問・資格・教育'), (6, '絵本・児童書'), (7, 'エンタメ'), (8, '雑誌・ムック'), (9, 'その他')], default=0, verbose_name='カテゴリ'),
        ),
    ]
