# Generated by Django 3.0.3 on 2021-03-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0007_auto_20210308_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='at_created',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='出品日'),
        ),
    ]
