# Generated by Django 3.0.3 on 2021-03-10 00:00

import cross_book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0008_item_at_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=cross_book.models.get_image_filename, verbose_name='画像')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cross_book.Item')),
            ],
        ),
    ]
