# Generated by Django 3.1.3 on 2021-04-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='new_message',
            field=models.BooleanField(default=True),
        ),
    ]
