# Generated by Django 3.0.3 on 2021-03-30 02:50

import cross_book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0011_auto_20210330_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default='選択してください', max_length=255, validators=[cross_book.models.Item.validate_category], verbose_name='カテゴリ'),
        ),
    ]
