# Generated by Django 3.1.3 on 2021-06-16 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0015_trade_trader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='trader',
        ),
    ]
