# Generated by Django 3.1.3 on 2021-06-17 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0016_remove_trade_trader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeinfo',
            old_name='trade_ID',
            new_name='trade',
        ),
        migrations.RenameField(
            model_name='trademessage',
            old_name='trade_ID',
            new_name='trade',
        ),
    ]
