# Generated by Django 3.1.3 on 2021-06-27 02:19

import cross_book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0019_auto_20210618_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=cross_book.models.get_image_filename, verbose_name=''),
        ),
    ]
