# Generated by Django 3.1.3 on 2021-06-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_book', '0020_auto_20210627_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_messages__created_at']},
        ),
    ]
